<?php

namespace Plugin\CMBlogPro42\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\CMBlogPro42\Entity\BlogSort;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;

/**
 * BlogSortRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogSortRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, BlogSort::class);
    }

    /**
     * 表示順覧を取得する.
     *
     * @return BlogSort[] 記事表示順の配列
     */
    public function getList()
    {
        $qb = $this->createQueryBuilder('bs')->orderBy('bs.sort_no', 'ASC');
        return $qb->getQuery()->getResult();
    }
}
