<?php

namespace Plugin\CMBlogPro42\Repository;

use Eccube\Repository\AbstractRepository;
use Plugin\CMBlogPro42\Entity\BlogStatus;
use Doctrine\Persistence\ManagerRegistry as RegistryInterface;

/**
 * BlogStatusRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlogStatusRepository extends AbstractRepository
{
    public function __construct(RegistryInterface $registry)
    {
        parent::__construct($registry, BlogStatus::class);
    }
}
